trigger:
  branches:
    include:
      - main

steps:
- checkout: self

- script: |
    # Initialize Terraform
    ls -l
    cd $(Build.SourcesDirectory)/terraform
    ls -l
    terraform init
    terraform plan
    terraform apply -auto-approve